{
    zigbeeModel: [
        'owvfni3\u0000', 'owvfni3', 'u1rkty3', 'aabybja', // Curtain motors
        'mcdj3aq', 'mcdj3aq\u0000', // Tubular motors
    ],
        fingerprint: [
            // Curtain motors:
            { modelID: 'TS0601', manufacturerName: '_TZE200_5zbp6j0u' },
            { modelID: 'TS0601', manufacturerName: '_TZE200_nkoabg8w' },
            { modelID: 'TS0601', manufacturerName: '_TZE200_xuzcvlku' },
            { modelID: 'TS0601', manufacturerName: '_TZE200_4vobcgd3' },
            { modelID: 'TS0601', manufacturerName: '_TZE200_nogaemzt' },
            { modelID: 'TS0601', manufacturerName: '_TZE200_r0jdjrvi' },
            { modelID: 'TS0601', manufacturerName: '_TZE200_pk0sfzvr' },
            { modelID: 'TS0601', manufacturerName: '_TZE200_fdtjuw7u' },
            { modelID: 'TS0601', manufacturerName: '_TZE200_zpzndjez' },
            { modelID: 'TS0601', manufacturerName: '_TZE200_wmcdj3aq' },
            { modelID: 'TS0601', manufacturerName: '_TZE200_cowvfni3' },
            { modelID: 'TS0601', manufacturerName: '_TZE200_rddyvrci' },
            { modelID: 'TS0601', manufacturerName: '_TZE200_nueqqe6k' },
            { modelID: 'TS0601', manufacturerName: '_TZE200_bqcqqjpb' },
            { modelID: 'TS0601', manufacturerName: '_TZE200_xaabybja' },
            { modelID: 'TS0601', manufacturerName: '_TZE200_rmymn92d' },
            { modelID: 'TS0601', manufacturerName: '_TZE200_feolm6rk' },
            { modelID: 'TS0601', manufacturerName: '_TZE200_3i3exuay' },
            { modelID: 'TS0601', manufacturerName: '_TZE200_tvrvdj6o' },
            { modelID: 'zo2pocs\u0000', manufacturerName: '_TYST11_fzo2pocs' },
            { modelID: 'TS0601', manufacturerName: '_TZE200_cf1sl3tj' },
            { modelID: 'TS0601', manufacturerName: '_TZE200_b2u1drdv' },
            { modelID: 'TS0601', manufacturerName: '_TZE200_ol5jlkkr' },
            { modelID: 'TS0601', manufacturerName: '_TZE204_guvc7pdy' },
            { modelID: 'TS0601', manufacturerName: '_TZE200_zxxfv8wi' },
            // Roller blinds:
            { modelID: 'TS0601', manufacturerName: '_TZE200_fctwhugx' },
            { modelID: 'TS0601', manufacturerName: '_TZE200_hsgrhjpf' },
            { modelID: 'TS0601', manufacturerName: '_TZE200_pw7mji0l' },
            // Window pushers:
            { modelID: 'TS0601', manufacturerName: '_TZE200_g5wdnuow' },
            // Tubular motors:
            { modelID: 'TS0601', manufacturerName: '_TZE200_5sbebbzs' },
            { modelID: 'TS0601', manufacturerName: '_TZE200_udank5zs' },
            { modelID: 'TS0601', manufacturerName: '_TZE200_zuz7f94z' },
            { modelID: 'TS0601', manufacturerName: '_TZE200_nv6nxo0c' },
            { modelID: 'TS0601', manufacturerName: '_TZE200_3ylew7b4' },
            { modelID: 'TS0601', manufacturerName: '_TZE200_llm0epxg' },
            { modelID: 'TS0601', manufacturerName: '_TZE200_n1aauwb4' },
            { modelID: 'TS0601', manufacturerName: '_TZE200_xu4a5rhj' },
            { modelID: 'TS0601', manufacturerName: '_TZE204_r0jdjrvi' },
            { modelID: 'TS0601', manufacturerName: '_TZE200_nw1r9hp6' },
            { modelID: 'TS0601', manufacturerName: '_TZE200_bjzrowv2' },
            { modelID: 'TS0601', manufacturerName: '_TZE200_axgvo9jh' },
            { modelID: 'TS0601', manufacturerName: '_TZE200_bv1jcqqu' },
            { modelID: 'TS0601', manufacturerName: '_TZE200_7eue9vhc' },
        ],
            model: 'TS0601_cover_1',
                vendor: 'TuYa',
                    description: 'Curtain motor/roller blind motor/window pusher/tubular motor',
                        whiteLabel: [
                            { vendor: 'Yushun', model: 'YS-MT750' },
                            tuya.whitelabel('Yushun', 'YS-MT750L', 'Curtain motor', ['_TZE200_bqcqqjpb']),
                            { vendor: 'Zemismart', model: 'ZM79E-DT' },
                            { vendor: 'Binthen', model: 'BCM100D' },
                            { vendor: 'Binthen', model: 'CV01A' },
                            { vendor: 'Zemismart', model: 'M515EGB' },
                            { vendor: 'OZ Smart Things', model: 'ZM85EL-1Z' },
                            { vendor: 'TuYa', model: 'M515EGZT' },
                            { vendor: 'TuYa', model: 'DT82LEMA-1.2N' },
                            { vendor: 'TuYa', model: 'ZD82TN', description: 'Curtain motor' },
                            { vendor: 'Larkkey', model: 'ZSTY-SM-1SRZG-EU' },
                            { vendor: 'Zemismart', model: 'AM43', description: 'Roller blind motor' },
                            { vendor: 'Zemismart', model: 'M2805EGBZTN', description: 'Tubular motor' },
                            { vendor: 'Zemismart', model: 'BCM500DS-TYZ', description: 'Curtain motor' },
                            { vendor: 'A-OK', model: 'AM25', description: 'Tubular motor' },
                            { vendor: 'Alutech', model: 'AM/R-Sm', description: 'Tubular motor' },
                            tuya.whitelabel('Shenzhen Golden Security Technology', 'GM46', 'Curtain motor', ['_TZE204_guvc7pdy']),
                            tuya.whitelabel('Zemismart', 'ZM85EL-2Z', 'Roman Rod I type U curtains track', ['_TZE200_cf1sl3tj', '_TZE200_nw1r9hp6']),
                            { vendor: 'Quoya', model: 'AT8510-TY' },
                            tuya.whitelabel('Somgoms', 'ZSTY-SM-1DMZG-US-W_1', 'Curtain switch', ['_TZE200_axgvo9jh']),
                            tuya.whitelabel('Zemismart', 'ZM25RX-08/30', 'Tubular motor', ['_TZE200_bv1jcqqu', '_TZE200_7eue9vhc']),
                            tuya.whitelabel('HUARUI', 'CMD900LE', 'Lithium battery intelligent curtain opening and closing motor', ['_TZE200_zxxfv8wi']),
                        ],
                            fromZigbee: [legacy.fromZigbee.tuya_cover, fz.ignore_basic_report],
                                toZigbee: [legacy.toZigbee.tuya_cover_control, legacy.toZigbee.tuya_cover_options],
                                    exposes: [
                                        e.cover_position().setAccess('position', ea.STATE_SET),
                                        e.composite('options', 'options', ea.STATE_SET)
                                            .withFeature(e.numeric('motor_speed', ea.STATE_SET)
                                                .withValueMin(0).withValueMax(255).withDescription('Motor speed'))
                                            .withFeature(e.binary('reverse_direction', ea.STATE_SET, true, false)
                                                .withDescription('Reverse the motor direction'))],
    },